default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: bmi_development

test:
  <<: *default
  database: bmi_test

production:
  <<: *default
  database: bmi_production
